before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: git-hint
    main: ./main.go
    ldflags: -s -w
    binary: git-hint
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
